### ISSUE TITLE
Unable to build this quickstart as native application when using Hazelcast locking feature

### ISSUE THREAD

**Issue by dcdh** [hazelcast-guides/hazelcast-quarkus#74]
Hello,

I am unable to build a native application using Hazelcast locking feature.

**Steps to reproduce**

1. git clone https://github.com/hazelcast-guides/hazelcast-client-quarkus.git
2. update `put` method in `CommandController` likes this (this is just for reproducing the issue):
```java
    @POST
    @Path("/put")
    @Produces(MediaType.APPLICATION_JSON)
    public CommandResponse put(@QueryParam("key") String key, @QueryParam("value") String value) {
        hazelcastInstance.getCPSubsystem().getLock("lock");// Problematic call.
        retrieveMap().put(key, value);
        return new CommandResponse(value, containerName);
    }
```
3. mvn clean package -Pnative -Dnative-image.docker-build=true

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< com.hazelcast:hazelcast-quarkus-guide >----------------
[INFO] Building hazelcast-quarkus-guide 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hazelcast-quarkus-guide ---
[INFO] Deleting /home/damien/IdeaProjects/hazelcast-client-quarkus/target
[INFO] 
[INFO] --- quarkus-maven-plugin:1.9.0.Final:generate-code (default) @ hazelcast-quarkus-guide ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hazelcast-quarkus-guide ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/damien/IdeaProjects/hazelcast-client-quarkus/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hazelcast-quarkus-guide ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /home/damien/IdeaProjects/hazelcast-client-quarkus/target/classes
[INFO] 
[INFO] --- quarkus-maven-plugin:1.9.0.Final:generate-code-tests (default) @ hazelcast-quarkus-guide ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hazelcast-quarkus-guide ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ hazelcast-quarkus-guide ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ hazelcast-quarkus-guide ---
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ hazelcast-quarkus-guide ---
[INFO] Building jar: /home/damien/IdeaProjects/hazelcast-client-quarkus/target/hazelcast-quarkus-guide-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:1.9.0.Final:build (default) @ hazelcast-quarkus-guide ---
[INFO] [org.jboss.threads] JBoss Threads version 3.1.1.Final
[INFO] [io.quarkus.arc.processor.BeanProcessor] Found unrecommended usage of private members (use package-private instead) in application beans:
        - @Inject field guides.hazelcast.quarkus.CommandController#containerName
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/damien/IdeaProjects/hazelcast-client-quarkus/target/hazelcast-quarkus-guide-1.0-SNAPSHOT-native-image-source-jar/hazelcast-quarkus-guide-1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/damien/IdeaProjects/hazelcast-client-quarkus/target/hazelcast-quarkus-guide-1.0-SNAPSHOT-native-image-source-jar/hazelcast-quarkus-guide-1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.2.0 (Java Version 11.0.8)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /usr/lib/jvm/graalvm/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true -J-Duser.language=fr -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -jar hazelcast-quarkus-guide-1.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace hazelcast-quarkus-guide-1.0-SNAPSHOT-runner
[hazelcast-quarkus-guide-1.0-SNAPSHOT-runner:70961]    classlist:   4 649,95 ms,  1,19 GB
[hazelcast-quarkus-guide-1.0-SNAPSHOT-runner:70961]        (cap):     475,64 ms,  1,19 GB
[hazelcast-quarkus-guide-1.0-SNAPSHOT-runner:70961]        setup:   1 481,54 ms,  1,19 GB
18:33:48,869 WARNING [com.haz.ins.imp.HazelcastInstanceFactory] Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
18:33:57,035 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
[hazelcast-quarkus-guide-1.0-SNAPSHOT-runner:70961]     (clinit):     391,97 ms,  5,42 GB
[hazelcast-quarkus-guide-1.0-SNAPSHOT-runner:70961]   (typeflow):  14 937,49 ms,  5,42 GB
[hazelcast-quarkus-guide-1.0-SNAPSHOT-runner:70961]    (objects):  13 856,10 ms,  5,42 GB
[hazelcast-quarkus-guide-1.0-SNAPSHOT-runner:70961]   (features):     670,73 ms,  5,42 GB
[hazelcast-quarkus-guide-1.0-SNAPSHOT-runner:70961]     analysis:  31 041,09 ms,  5,42 GB
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.findConstructor(Class, MethodType): 
        at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1260)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.tryWrapInSameClass(AbstractInvocationFuture.java:1963)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapError(AbstractInvocationFuture.java:1945)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1931)
        at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1400)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:593)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:569)
        at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.getGroupId(ClientRaftProxyFactory.java:124)
        at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.createProxy(ClientRaftProxyFactory.java:72)
        at com.hazelcast.client.cp.internal.CPSubsystemImpl.getLock(CPSubsystemImpl.java:81)
        at guides.hazelcast.quarkus.CommandController.put(CommandController.java:32)
        at com.oracle.svm.reflect.CommandController_put_29a20117b9e28d8a720e71a47cd0428f960d8765_137.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy215.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getLinkage(JNIReflectionDictionary.java:146)
        at com.oracle.svm.jni.functions.JNIFunctions.RegisterNatives(JNIFunctions.java:350)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_RegisterNatives_7728ce15b57af339792ad95c60f247990e0df65e(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.findConstructor(Class, MethodType): 
        at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1260)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.tryWrapInSameClass(AbstractInvocationFuture.java:1963)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapError(AbstractInvocationFuture.java:1945)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1931)
        at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1400)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:593)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:569)
        at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.getGroupId(ClientRaftProxyFactory.java:124)
        at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.createProxy(ClientRaftProxyFactory.java:72)
        at com.hazelcast.client.cp.internal.CPSubsystemImpl.getLock(CPSubsystemImpl.java:81)
        at guides.hazelcast.quarkus.CommandController.put(CommandController.java:32)
        at com.oracle.svm.reflect.CommandController_put_29a20117b9e28d8a720e71a47cd0428f960d8765_137.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy215.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getLinkage(JNIReflectionDictionary.java:146)
        at com.oracle.svm.jni.functions.JNIFunctions.RegisterNatives(JNIFunctions.java:350)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_RegisterNatives_7728ce15b57af339792ad95c60f247990e0df65e(generated:0)

        at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.findConstructor(Class, MethodType): 
        at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1260)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.tryWrapInSameClass(AbstractInvocationFuture.java:1963)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapError(AbstractInvocationFuture.java:1945)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1931)
        at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1400)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:593)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:569)
        at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.getGroupId(ClientRaftProxyFactory.java:124)
        at com.hazelcast.client.cp.internal.datastructures.proxy.ClientRaftProxyFactory.createProxy(ClientRaftProxyFactory.java:72)
        at com.hazelcast.client.cp.internal.CPSubsystemImpl.getLock(CPSubsystemImpl.java:81)
        at guides.hazelcast.quarkus.CommandController.put(CommandController.java:32)
        at com.oracle.svm.reflect.CommandController_put_29a20117b9e28d8a720e71a47cd0428f960d8765_137.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:122)
        at com.sun.proxy.$Proxy215.hashCode(Unknown Source)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getLinkage(JNIReflectionDictionary.java:146)
        at com.oracle.svm.jni.functions.JNIFunctions.RegisterNatives(JNIFunctions.java:350)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_RegisterNatives_7728ce15b57af339792ad95c60f247990e0df65e(generated:0)

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:762)
        ... 8 more
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:115)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:113)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:113)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:206)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:186)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:76)
        at com.oracle.graal.pointsto.infrastructure.WrappedSignature.getReturnType(WrappedSignature.java:75)
        at com.oracle.graal.pointsto.flow.MethodFlowsGraph.<init>(MethodFlowsGraph.java:115)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.<init>(MethodTypeFlow.java:73)
        at com.oracle.graal.pointsto.meta.AnalysisMethod.<init>(AnalysisMethod.java:142)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.createMethod(AnalysisUniverse.java:419)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:407)
        at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupMethod(WrappedConstantPool.java:125)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupMethodInPool(BytecodeParser.java:4313)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.lookupMethodInPool(SharedGraphBuilderPhase.java:113)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:4307)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1691)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5338)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3413)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3220)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1090)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:984)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:74)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:368)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
        at com.oracle.graal.pointsto.flow.SourceTypeFlowBase.update(SourceTypeFlowBase.java:144)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:552)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        ... 5 more
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Expected behavior**
The build produces a native image.

**Additional informations**

```
[damien@localhost hazelcast-client-quarkus]$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 11.0.8, vendor: GraalVM Community, runtime: /usr/lib/jvm/graalvm-ce-java11-20.2.0
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "5.5.6-1.el7.elrepo.x86_64", arch: "amd64", family: "unix"
```

```
[damien@localhost hazelcast-client-quarkus]$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)
```

**Comment by dcdh** [comment]
Maybe we should wait for this feature to be implemented : https://github.com/oracle/graal/issues/2761

**Comment by dcdh** [comment]
I've created this endpoint

```java
    @GET
    @Path("/lock")
    public void lock() {
        logger.info("lock");
        final FencedLock fencedLock = hazelcastInstance.getCPSubsystem().getLock("lock");
        try {
            fencedLock.lock();
            logger.info("locked");
        } finally {
            fencedLock.unlock();
            logger.info("unlocked");
        }
    }
```
and rebuild it using this conf in my pom.xml:

```xml
            <properties>
                <quarkus.package.type>native</quarkus.package.type>
                <quarkus.native.additional-build-args>--report-unsupported-elements-at-runtime</quarkus.native.additional-build-args>
            </properties>
```
The build as passed because unsupported elements are skipped during build phase.

Next doing this curl url `curl http://localhost:8080/hazelcast/lock`

```
quarkus-service1    | 2020-10-27 19:29:47,293 INFO  [gui.haz.qua.CommandController] (executor-thread-1) lock
member1             | Oct 27, 2020 7:29:47 PM com.hazelcast.internal.partition.impl.PartitionStateManager
member1             | INFO: [192.168.112.2]:5701 [dev] [4.0.3] Initializing cluster partition table arrangement...
member1             | Oct 27, 2020 7:29:47 PM com.hazelcast.cp.internal.session.RaftSessionService
member1             | INFO: [192.168.112.2]:5701 [dev] [4.0.3] Created new session: 1 in CPGroupId{name='lock', seed=0, groupId=188} for CLIENT -> [192.168.112.5]:58029
member2             | Oct 27, 2020 7:29:47 PM com.hazelcast.cp.internal.session.RaftSessionService
member2             | INFO: [192.168.112.3]:5701 [dev] [4.0.3] Created new session: 1 in CPGroupId{name='lock', seed=0, groupId=188} for CLIENT -> [192.168.112.5]:58029
quarkus-service1    | 2020-10-27 19:29:47,323 INFO  [gui.haz.qua.CommandController] (executor-thread-1) locked
quarkus-service1    | 2020-10-27 19:29:47,326 INFO  [gui.haz.qua.CommandController] (executor-thread-1) unlocked
```

It works. I do not know why ... but it means that I can have other issue I will not see them until I run the application.

**Comment by pivovarit** [comment]
Ok, that's something new... :)

Thank you so much for reporting this. Will investigate in-depth next week.

~Btw, this issue belongs to https://github.com/hazelcast/quarkus-hazelcast-client and I will transfer it there~
